const USER_ROLES = {
  SUPERADMIN: "SUPERADMIN",
  TRANSPORT: "TRANSPORT",
  SHOOT: "SHOOT",
  CUSTOMER: "CUSTOMER",
};

const OUR_WORK_TYPES = {
  IMAGE: "IMAGE",
  THREE_SIXTY: "360_VIEW",
  VIDEO: "VIDEO",
  SHORT_VIDEO: "SHORT_VIDEO",
};

export { USER_ROLES, OUR_WORK_TYPES };
